/**
 * Generate the offline icon bundle (DEV-250).
 *
 * Reads `ICON_REGISTRY` and extracts ONLY the referenced icons from the locally
 * installed `@iconify-json/*` sets into `src/shared/ui/icon/bundledIcons.generated.ts`.
 * The app registers that subset via `addCollection` at startup, so icons render
 * from bundled assets instead of the runtime Iconify CDN.
 *
 * Existence is checked OFFLINE here against the installed vendor sets: if a
 * registry source names an icon that does not exist in its set, this script
 * fails (non-zero exit) instead of shipping a silent runtime blank. Run:
 *
 *   bun run icons:bundle        # from app/frontend
 *
 * Only the used icons are emitted, so the bundle stays small even though the
 * full `@iconify-json/mdi` set is thousands of icons.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import type { IconifyJSON } from "@iconify/types";
import { getIcons } from "@iconify/utils";
import { icons as mdi } from "@iconify-json/mdi";
import { icons as lucide } from "@iconify-json/lucide";
import { icons as materialIconTheme } from "@iconify-json/material-icon-theme";
import { ICON_REGISTRY, type IconSource } from "../src/shared/ui/icon/registry";

// Every Iconify collection the registry is allowed to draw from must be listed
// here. A registry prefix with no entry is a hard error — we can't bundle a set
// we don't have installed as a dependency.
const COLLECTIONS: Record<string, IconifyJSON> = {
  mdi,
  lucide,
  "material-icon-theme": materialIconTheme,
};

type ParsedSource = { prefix: string; name: string; source: string };

function parseSource(source: string): ParsedSource {
  const colon = source.indexOf(":");
  if (colon <= 0 || colon === source.length - 1) {
    throw new Error(
      `Invalid Iconify source "${source}" — expected "<prefix>:<name>".`,
    );
  }
  return {
    prefix: source.slice(0, colon),
    name: source.slice(colon + 1),
    source,
  };
}

function collectSources(): ParsedSource[] {
  const seen = new Set<string>();
  const parsed: ParsedSource[] = [];
  // `satisfies` preserves each entry's narrow literal type (dropping optional
  // `pixel`); widen to IconSource[] via assignability (no cast) — same pattern
  // as resolveIconSource.ts.
  const entries: IconSource[] = Object.values(ICON_REGISTRY);
  for (const entry of entries) {
    const sources = entry.pixel !== undefined ? [entry.default, entry.pixel] : [entry.default];
    for (const source of sources) {
      if (seen.has(source)) continue;
      seen.add(source);
      parsed.push(parseSource(source));
    }
  }
  return parsed;
}

function main(): void {
  const sources = collectSources();

  // Group requested icon names by prefix.
  const namesByPrefix = new Map<string, string[]>();
  for (const { prefix, name } of sources) {
    const list = namesByPrefix.get(prefix) ?? [];
    list.push(name);
    namesByPrefix.set(prefix, list);
  }

  const collections: IconifyJSON[] = [];
  const missing: string[] = [];

  for (const [prefix, names] of namesByPrefix) {
    const set = COLLECTIONS[prefix];
    if (set === undefined) {
      throw new Error(
        `Registry references prefix "${prefix}" but no @iconify-json set is wired in generate-icon-bundle.ts. ` +
          `Add "@iconify-json/${prefix}" as a devDependency and register it in COLLECTIONS.`,
      );
    }
    const subset = getIcons(set, names, true);
    if (subset === null) {
      // No requested icon exists in this set.
      for (const name of names) missing.push(`${prefix}:${name}`);
      continue;
    }
    // `not_found` is present only when some names were missing.
    for (const name of subset.not_found ?? []) {
      missing.push(`${prefix}:${name}`);
    }
    // Drop the `not_found` marker from the shipped data (only useful here).
    const { not_found: _dropped, ...clean } = subset;
    collections.push(clean);
  }

  if (missing.length > 0) {
    console.error(
      `\n✖ ${missing.length} registry icon(s) do NOT exist in their vendor set:\n` +
        missing.map((s) => `   - ${s}`).join("\n") +
        `\n\nFix the source in registry.ts (or add the correct vendor set).\n`,
    );
    process.exit(1);
  }

  const header =
    "// AUTO-GENERATED by app/frontend/scripts/generate-icon-bundle.ts — DO NOT EDIT.\n" +
    "// Run `bun run icons:bundle` (frontend) to regenerate after changing registry.ts.\n" +
    'import type { IconifyJSON } from "@iconify/types";\n\n';
  const body =
    "export const BUNDLED_ICON_COLLECTIONS: readonly IconifyJSON[] = " +
    JSON.stringify(collections, null, 2) +
    ";\n";

  const outPath = join(
    dirname(fileURLToPath(import.meta.url)),
    "../src/shared/ui/icon/bundledIcons.generated.ts",
  );
  writeFileSync(outPath, header + body);

  const iconCount = sources.length;
  console.log(
    `✔ Bundled ${iconCount} icon(s) across ${collections.length} collection(s) → ${outPath}`,
  );
}

main();
