export const EFFECT_PARAMETER_NAME_MAP: Record<string, Record<string, string>> = {
  reverb: {
    ['room_size']: "roomSize",
    ['decay_time']: "decayTime",
    ['pre_delay']: "preDelay",
    ['dry_wet']: "wetLevel",
    wet: "wetLevel",
  },
  delay: {
    time: "delayTime",
    ['delay_time']: "delayTime",
    feedback: "feedback",
    ['dry_wet']: "wetLevel",
    wet: "wetLevel",
  },
  chorus: {
    frequency: "frequency",
    ['delay_time']: "delayTime",
    depth: "depth",
    spread: "spread",
    ['dry_wet']: "wetLevel",
  },
  compressor: {
    threshold: "threshold",
    ratio: "ratio",
    attack: "attack",
    release: "release",
    knee: "knee",
    ['makeup_gain']: "makeupGain",
    ['dry_wet']: "wetLevel",
  },
  filter: {
    frequency: "frequency",
    resonance: "Q",
    q: "Q",
    type: "type",
    ['dry_wet']: "wetLevel",
  },
  distortion: {
    distortion: "distortion",
    oversample: "oversample",
    ['dry_wet']: "wetLevel",
  },
  autofilter: {
    frequency: "frequency",
    ['base_frequency']: "baseFrequency",
    octaves: "octaves",
    ['filter_type']: "type",
    type: "type",
    ['dry_wet']: "wetLevel",
  },
  autopanner: {
    frequency: "frequency",
    depth: "depth",
    ['dry_wet']: "wetLevel",
  },
  autowah: {
    ['base_frequency']: "baseFrequency",
    octaves: "octaves",
    sensitivity: "sensitivity",
    q: "Q",
    ['dry_wet']: "wetLevel",
  },
  bitcrusher: {
    bits: "bits",
    ['dry_wet']: "wetLevel",
  },
  phaser: {
    frequency: "frequency",
    octaves: "octaves",
    ['base_frequency']: "baseFrequency",
    stages: "stages",
    q: "Q",
    ['dry_wet']: "wetLevel",
  },
  pingpongdelay: {
    ['delay_time']: "delayTime",
    feedback: "feedback",
    ['dry_wet']: "wetLevel",
    wet: "wetLevel",
  },
  stereowidener: {
    width: "width",
    ['dry_wet']: "wetLevel",
  },
  tremolo: {
    frequency: "frequency",
    depth: "depth",
    spread: "spread",
    ['dry_wet']: "wetLevel",
  },
  vibrato: {
    frequency: "frequency",
    depth: "depth",
    ['dry_wet']: "wetLevel",
  },
  graphiceq: {
    ['low_cut']: "lowCut",
    ['p1_freq']: "p1Freq",
    ['p2_freq']: "p2Freq",
    ['p3_freq']: "p3Freq",
    ['p4_freq']: "p4Freq",
    ['p5_freq']: "p5Freq",
    ['high_cut']: "highCut",
    ['p1_q']: "p1Q",
    ['p2_q']: "p2Q",
    ['p3_q']: "p3Q",
    ['p4_q']: "p4Q",
    ['p5_q']: "p5Q",
    ['p1_vol']: "p1Vol",
    ['p2_vol']: "p2Vol",
    ['p3_vol']: "p3Vol",
    ['p4_vol']: "p4Vol",
    ['p5_vol']: "p5Vol",
  },
  autotune: {
    interval: "interval",
    ['retune_speed']: "retuneSpeed",
    latency: "blockMs",
    formant: "formant",
    ['dry_wet']: "wetLevel",
    wet: "wetLevel",
  },
  vocoder: {
    ['carrier_base']: "carrierMode",
    voices: "degrees",
    ['carrier_wave']: "carrierWave",
    ['unison_voices']: "unison",
    detune: "spreadCents",
    ['octave_layer']: "octaveMix",
    ['band_q']: "bandQ",
    ['band_count']: "bandCount",
    ['band_spacing']: "melSpacing",
    ['noise_crossover']: "noiseCrossHz",
    ['noise_hf']: "noiseHighAmount",
    ['unvoiced_noise']: "uvNoiseAmount",
    sibilance: "sibilancePassthrough",
    ['sibilance_cutoff']: "sibilanceHz",
    ['envelope_speed']: "envHz",
    ['hf_tilt']: "tiltDbOct",
    ['output_gain']: "outputGain",
    ['dry_wet']: "wetLevel",
  },
  ducker: {
    threshold: "threshold",
    amount: "amount",
    attack: "attack",
    release: "release",
    hold: "hold",
    ['dry_wet']: "wetLevel",
  },
  vocoderext: {
    ['band_q']: "bandQ",
    ['band_count']: "bandCount",
    ['band_spacing']: "melSpacing",
    ['noise_hf']: "noiseHighAmount",
    sibilance: "sibilancePassthrough",
    ['envelope_speed']: "envHz",
    ['hf_tilt']: "tiltDbOct",
    ['output_gain']: "outputGain",
    ['dry_wet']: "wetLevel",
  },
};

export const normalizeEffectParameterName = (name: string): string =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, "_");
