import { SynthParams } from '../types';
import { FACTORY_BASS_PRESETS } from './bassPresets';

export type SynthPresetCategory =
  | 'Bass'
  | 'Lead'
  | 'Pad'
  | 'Keys'
  | 'Pluck'
  | 'Brass'
  | 'FX'
  | 'User';

export interface SynthPresetCategoryMeta {
  id: SynthPresetCategory;
  label: string;
  shortLabel: string;
  badgeClass: string;
  description: string;
}

export const SYNTH_CATEGORIES: SynthPresetCategoryMeta[] = [
  {
    id: 'Bass',
    label: 'Bass',
    shortLabel: 'Bass',
    badgeClass: 'badge badge-accent',
    description: 'Sub-basses, 808s, reese, acid, and bassline tones',
  },
  {
    id: 'Lead',
    label: 'Lead',
    shortLabel: 'Lead',
    badgeClass: 'badge badge-secondary',
    description: 'Cutting leads, vocal sweeps, and melodic solo synthesizers',
  },
  {
    id: 'Pad',
    label: 'Pad',
    shortLabel: 'Pad',
    badgeClass: 'badge badge-primary',
    description: 'Lush ambient textures, string ensembles, and warm backdrops',
  },
  {
    id: 'Keys',
    label: 'Keys',
    shortLabel: 'Keys',
    badgeClass: 'badge badge-accent badge-outline',
    description: 'Electric pianos, bells, chimes, and organ keyboards',
  },
  {
    id: 'Pluck',
    label: 'Pluck',
    shortLabel: 'Pluck',
    badgeClass: 'badge badge-primary badge-outline',
    description: 'Snappy transients, percussive mallets, and short plucks',
  },
  {
    id: 'Brass',
    label: 'Brass',
    shortLabel: 'Brass',
    badgeClass: 'badge badge-primary badge-soft',
    description: 'Analog synth horns, power stabs, and fanfare swells',
  },
  {
    id: 'FX',
    label: 'FX',
    shortLabel: 'FX',
    badgeClass: 'badge badge-secondary badge-soft',
    description: 'Atmospheric drones, sweeps, noise risers, and sci-fi zaps',
  },
  {
    id: 'User',
    label: 'Custom / User',
    shortLabel: 'Custom',
    badgeClass: 'badge badge-success badge-outline',
    description: 'Custom user patches saved to browser storage',
  },
];

export interface SynthPresetItem {
  id: string;
  name: string;
  category: SynthPresetCategory;
  params: Partial<SynthParams>;
  isFactory?: boolean;
  createdAt?: number;
  author?: string;
  description?: string;
}

export const FACTORY_PRESETS: SynthPresetItem[] = [
  {
    id: 'factory-cosmic-lead',
    name: 'Cosmic Lead',
    category: 'Lead',
    isFactory: true,
    description: 'Bright soaring lead with detuned oscillators and a resonant filter sweep',
    params: {
      oscType: 'sawtooth',
      subOscVolume: 0.2,
      noiseVolume: 0.05,
      detune: 5,
      filterType: 'lowpass',
      filterCutoff: 2800,
      filterResonance: 3.5,
      filterEnvAmount: 1500,
      attack: 0.02,
      decay: 0.3,
      sustain: 0.7,
      release: 0.4,
      filterAttack: 0.02,
      filterDecay: 0.3,
      filterSustain: 0.25,
      filterRelease: 0.4,
      lfoRate: 4,
      lfoDepth: 0.15,
      lfoTarget: 'cutoff',
      octave: 0,
    },
  },
  {
    id: 'factory-808-deep-bass',
    name: '808 Deep Bass',
    category: 'Bass',
    isFactory: true,
    description: 'Sub-heavy pure sine bass with punchy envelope decay',
    params: {
      oscType: 'sine',
      subOscVolume: 0.8,
      noiseVolume: 0.0,
      detune: 0,
      filterType: 'lowpass',
      filterCutoff: 450,
      filterResonance: 1.5,
      filterEnvAmount: 300,
      attack: 0.005,
      decay: 0.5,
      sustain: 0.4,
      release: 0.35,
      filterAttack: 0.005,
      filterDecay: 0.5,
      filterSustain: 0,
      filterRelease: 0.35,
      lfoRate: 1,
      lfoDepth: 0.0,
      lfoTarget: 'pitch',
      octave: -1,
    },
  },
  {
    id: 'factory-warm-polypad',
    name: 'Warm PolyPad',
    category: 'Pad',
    isFactory: true,
    description: 'Lush ambient triangle pad whose filter slowly opens and settles',
    params: {
      oscType: 'triangle',
      subOscVolume: 0.3,
      noiseVolume: 0.02,
      detune: 10,
      filterType: 'lowpass',
      filterCutoff: 1400,
      filterResonance: 2.0,
      filterEnvAmount: 600,
      attack: 0.4,
      decay: 0.8,
      sustain: 0.85,
      release: 1.2,
      filterAttack: 0.6,
      filterDecay: 0.8,
      filterSustain: 0.5,
      filterRelease: 1.2,
      lfoRate: 0.5,
      lfoDepth: 0.25,
      lfoTarget: 'cutoff',
      octave: 0,
    },
  },
  {
    id: 'factory-acid-synth',
    name: 'Acid Synth',
    category: 'Bass',
    isFactory: true,
    description: 'High resonance TB-303 style squelch with fast snappy envelope',
    params: {
      oscType: 'sawtooth',
      subOscVolume: 0.4,
      noiseVolume: 0.0,
      detune: 0,
      filterType: 'lowpass',
      filterCutoff: 1200,
      filterResonance: 12.0,
      filterEnvAmount: 3500,
      attack: 0.005,
      decay: 0.2,
      sustain: 0.15,
      release: 0.2,
      filterAttack: 0.005,
      filterDecay: 0.25,
      filterSustain: 0,
      filterRelease: 0.2,
      lfoRate: 6,
      lfoDepth: 0.4,
      lfoTarget: 'cutoff',
      octave: -1,
    },
  },
  {
    id: 'factory-dream-keys',
    name: 'Dream Keys',
    category: 'Keys',
    isFactory: true,
    description: 'Soft chime-like electric keyboard tones with delicate vibrato',
    params: {
      oscType: 'sine',
      subOscVolume: 0.1,
      noiseVolume: 0.01,
      detune: 4,
      filterType: 'lowpass',
      filterCutoff: 3200,
      filterResonance: 1.2,
      filterEnvAmount: 800,
      attack: 0.01,
      decay: 0.6,
      sustain: 0.4,
      release: 0.6,
      filterAttack: 0.01,
      filterDecay: 0.6,
      filterSustain: 0.3,
      filterRelease: 0.6,
      lfoRate: 2.5,
      lfoDepth: 0.1,
      lfoTarget: 'pitch',
      octave: 0,
    },
  },
  {
    id: 'factory-pluck',
    name: 'Neon Pluck',
    category: 'Pluck',
    isFactory: true,
    description: 'Crisp square-wave pluck with instant attack and fast decay',
    params: {
      oscType: 'square',
      subOscVolume: 0.2,
      noiseVolume: 0.05,
      detune: 8,
      filterType: 'lowpass',
      filterCutoff: 4000,
      filterResonance: 4.0,
      filterEnvAmount: 2800,
      attack: 0.005,
      decay: 0.15,
      sustain: 0.05,
      release: 0.25,
      filterAttack: 0.005,
      filterDecay: 0.15,
      filterSustain: 0,
      filterRelease: 0.25,
      lfoRate: 0.5,
      lfoDepth: 0.0,
      lfoTarget: 'cutoff',
      octave: 0,
    },
  },
  {
    id: 'factory-vintage-brass',
    name: 'Vintage Brass',
    category: 'Brass',
    isFactory: true,
    description: 'Analog synth brass with a swelling filter and tremolo modulation',
    params: {
      oscType: 'sawtooth',
      subOscVolume: 0.35,
      noiseVolume: 0.03,
      detune: 12,
      filterType: 'lowpass',
      filterCutoff: 2100,
      filterResonance: 2.8,
      filterEnvAmount: 1800,
      attack: 0.08,
      decay: 0.4,
      sustain: 0.6,
      release: 0.5,
      filterAttack: 0.12,
      filterDecay: 0.4,
      filterSustain: 0.45,
      filterRelease: 0.5,
      lfoRate: 5,
      lfoDepth: 0.15,
      lfoTarget: 'volume',
      octave: 0,
    },
  },
  {
    id: 'factory-cyber-drone',
    name: 'Cyber Drone',
    category: 'FX',
    isFactory: true,
    description: 'Cinematic sweeping bandpass drone with slow undulating LFO',
    params: {
      oscType: 'square',
      subOscVolume: 0.6,
      noiseVolume: 0.1,
      detune: 18,
      filterType: 'bandpass',
      filterCutoff: 1100,
      filterResonance: 6.0,
      filterEnvAmount: 400,
      attack: 0.8,
      decay: 1.5,
      sustain: 0.9,
      release: 2.0,
      filterAttack: 1.0,
      filterDecay: 1.5,
      filterSustain: 0.6,
      filterRelease: 2.0,
      lfoRate: 0.2,
      lfoDepth: 0.4,
      lfoTarget: 'cutoff',
      octave: -1,
    },
  },
  {
    id: 'factory-string-ensemble',
    name: 'String Ensemble',
    category: 'Pad',
    isFactory: true,
    description: 'Slow-attack detuned saw pad that blooms open like bowed strings',
    params: {
      oscType: 'sawtooth',
      subOscVolume: 0.25,
      noiseVolume: 0.02,
      detune: 14,
      filterType: 'lowpass',
      filterCutoff: 1900,
      filterResonance: 2.2,
      filterEnvAmount: 700,
      attack: 0.35,
      decay: 0.9,
      sustain: 0.8,
      release: 1.5,
      filterAttack: 0.5,
      filterDecay: 1.4,
      filterSustain: 0.5,
      filterRelease: 1.5,
      lfoRate: 0.6,
      lfoDepth: 0.2,
      lfoTarget: 'cutoff',
      octave: 0,
    },
  },
  {
    id: 'factory-wobble-bass',
    name: 'Wobble Bass',
    category: 'Bass',
    isFactory: true,
    description: 'Dubstep-style wobble driven by a fast LFO on the filter cutoff',
    params: {
      oscType: 'sawtooth',
      subOscVolume: 0.5,
      noiseVolume: 0.0,
      detune: 0,
      filterType: 'lowpass',
      filterCutoff: 800,
      filterResonance: 6.0,
      filterEnvAmount: 300,
      attack: 0.005,
      decay: 0.3,
      sustain: 0.5,
      release: 0.3,
      filterAttack: 0.005,
      filterDecay: 0.3,
      filterSustain: 0.1,
      filterRelease: 0.3,
      lfoRate: 4.0,
      lfoDepth: 0.5,
      lfoTarget: 'cutoff',
      octave: -2,
    },
  },
  {
    id: 'factory-glocken-bell',
    name: 'Glocken Bell',
    category: 'Keys',
    isFactory: true,
    description: 'Pure bell tone with a long crystalline decay, one octave up',
    params: {
      oscType: 'sine',
      subOscVolume: 0.05,
      noiseVolume: 0.0,
      detune: 2,
      filterType: 'lowpass',
      filterCutoff: 5000,
      filterResonance: 1.0,
      filterEnvAmount: 500,
      attack: 0.002,
      decay: 1.8,
      sustain: 0.05,
      release: 1.2,
      filterAttack: 0.002,
      filterDecay: 1.0,
      filterSustain: 0,
      filterRelease: 1.2,
      lfoRate: 0.3,
      lfoDepth: 0.0,
      lfoTarget: 'cutoff',
      octave: 1,
    },
  },
  {
    id: 'factory-vocal-lead',
    name: 'Vocal Lead',
    category: 'Lead',
    isFactory: true,
    description: 'Expressive lead with a formant-like filter swell and vibrato',
    params: {
      oscType: 'sawtooth',
      subOscVolume: 0.2,
      noiseVolume: 0.03,
      detune: 6,
      filterType: 'lowpass',
      filterCutoff: 3200,
      filterResonance: 5.0,
      filterEnvAmount: 1600,
      attack: 0.15,
      decay: 0.4,
      sustain: 0.65,
      release: 0.5,
      filterAttack: 0.15,
      filterDecay: 0.5,
      filterSustain: 0.2,
      filterRelease: 0.5,
      lfoRate: 5.0,
      lfoDepth: 0.12,
      lfoTarget: 'pitch',
      octave: 0,
    },
  },
  {
    id: 'factory-stab-brass',
    name: 'Stab Brass',
    category: 'Brass',
    isFactory: true,
    description: 'Punchy house stab with a lightning-fast filter snap',
    params: {
      oscType: 'square',
      subOscVolume: 0.4,
      noiseVolume: 0.02,
      detune: 10,
      filterType: 'lowpass',
      filterCutoff: 2600,
      filterResonance: 3.0,
      filterEnvAmount: 2400,
      attack: 0.005,
      decay: 0.35,
      sustain: 0.2,
      release: 0.3,
      filterAttack: 0.005,
      filterDecay: 0.25,
      filterSustain: 0,
      filterRelease: 0.3,
      lfoRate: 0.5,
      lfoDepth: 0.0,
      lfoTarget: 'volume',
      octave: 0,
    },
  },
  {
    id: 'factory-dark-sub-pad',
    name: 'Dark Sub Pad',
    category: 'Pad',
    isFactory: true,
    description: 'Deep sub-heavy pad that stays dark and open underneath',
    params: {
      oscType: 'triangle',
      subOscVolume: 0.7,
      noiseVolume: 0.01,
      detune: 8,
      filterType: 'lowpass',
      filterCutoff: 700,
      filterResonance: 1.8,
      filterEnvAmount: 300,
      attack: 0.5,
      decay: 1.2,
      sustain: 0.85,
      release: 2.0,
      filterAttack: 0.6,
      filterDecay: 1.5,
      filterSustain: 0.7,
      filterRelease: 2.0,
      lfoRate: 0.15,
      lfoDepth: 0.15,
      lfoTarget: 'cutoff',
      octave: -1,
    },
  },
  {
    id: 'factory-laser-fx',
    name: 'Laser FX',
    category: 'FX',
    isFactory: true,
    description: 'Sci-fi zaps: highpass sweep with aggressive pitch LFO wobble',
    params: {
      oscType: 'sawtooth',
      subOscVolume: 0.0,
      noiseVolume: 0.05,
      detune: 0,
      filterType: 'highpass',
      filterCutoff: 1200,
      filterResonance: 8.0,
      filterEnvAmount: 2500,
      attack: 0.3,
      decay: 0.4,
      sustain: 0.6,
      release: 1.0,
      filterAttack: 0.3,
      filterDecay: 0.5,
      filterSustain: 0.4,
      filterRelease: 1.0,
      lfoRate: 8.0,
      lfoDepth: 0.5,
      lfoTarget: 'pitch',
      octave: 1,
    },
  },
  {
    id: 'factory-mellow-epiano',
    name: 'Mellow E-Piano',
    category: 'Keys',
    isFactory: true,
    description: 'Soft electric piano with gentle tremolo and a rounded filter',
    params: {
      oscType: 'sine',
      subOscVolume: 0.15,
      noiseVolume: 0.01,
      detune: 3,
      filterType: 'lowpass',
      filterCutoff: 2800,
      filterResonance: 1.5,
      filterEnvAmount: 400,
      attack: 0.02,
      decay: 0.9,
      sustain: 0.35,
      release: 0.8,
      filterAttack: 0.02,
      filterDecay: 0.9,
      filterSustain: 0.2,
      filterRelease: 0.8,
      lfoRate: 4.5,
      lfoDepth: 0.08,
      lfoTarget: 'volume',
      octave: 0,
    },
  },
  {
    id: 'factory-hyper-saw-lead',
    name: 'Hyper Saw Lead',
    category: 'Lead',
    isFactory: true,
    description: 'Massive stacked sawtooth lead with bright cutoff and snappy attack',
    params: {
      oscType: 'sawtooth',
      subOscVolume: 0.35,
      noiseVolume: 0.04,
      detune: 16,
      filterType: 'lowpass',
      filterCutoff: 3800,
      filterResonance: 2.2,
      filterEnvAmount: 2000,
      attack: 0.008,
      decay: 0.3,
      sustain: 0.75,
      release: 0.35,
      filterAttack: 0.008,
      filterDecay: 0.35,
      filterSustain: 0.3,
      filterRelease: 0.35,
      lfoRate: 3.5,
      lfoDepth: 0.08,
      lfoTarget: 'pitch',
      octave: 0,
    },
  },
  {
    id: 'factory-reese-sub-bass',
    name: 'Reese Sub Bass',
    category: 'Bass',
    isFactory: true,
    description: 'Warm chorused reese bass with subtle pitch detuning and sub weight',
    params: {
      oscType: 'sawtooth',
      subOscVolume: 0.7,
      noiseVolume: 0.0,
      detune: 14,
      filterType: 'lowpass',
      filterCutoff: 650,
      filterResonance: 2.5,
      filterEnvAmount: 400,
      attack: 0.02,
      decay: 0.4,
      sustain: 0.8,
      release: 0.4,
      filterAttack: 0.02,
      filterDecay: 0.4,
      filterSustain: 0.4,
      filterRelease: 0.4,
      lfoRate: 0.8,
      lfoDepth: 0.15,
      lfoTarget: 'cutoff',
      octave: -1,
    },
  },
  {
    id: 'factory-celestial-shimmer',
    name: 'Celestial Shimmer',
    category: 'Pad',
    isFactory: true,
    description: 'Dreamy high-register pad that blooms with slow ethereal movement',
    params: {
      oscType: 'sine',
      subOscVolume: 0.15,
      noiseVolume: 0.03,
      detune: 12,
      filterType: 'lowpass',
      filterCutoff: 2400,
      filterResonance: 3.0,
      filterEnvAmount: 1100,
      attack: 0.6,
      decay: 1.5,
      sustain: 0.9,
      release: 2.5,
      filterAttack: 0.8,
      filterDecay: 1.8,
      filterSustain: 0.6,
      filterRelease: 2.5,
      lfoRate: 0.4,
      lfoDepth: 0.3,
      lfoTarget: 'cutoff',
      octave: 1,
    },
  },
  {
    id: 'factory-fm-tine-piano',
    name: 'FM Tine Piano',
    category: 'Keys',
    isFactory: true,
    description: '80s digital electric piano chime with percussive key strike',
    params: {
      oscType: 'triangle',
      subOscVolume: 0.2,
      noiseVolume: 0.02,
      detune: 5,
      filterType: 'lowpass',
      filterCutoff: 3600,
      filterResonance: 2.0,
      filterEnvAmount: 1400,
      attack: 0.005,
      decay: 0.7,
      sustain: 0.3,
      release: 0.7,
      filterAttack: 0.005,
      filterDecay: 0.5,
      filterSustain: 0.15,
      filterRelease: 0.7,
      lfoRate: 3.0,
      lfoDepth: 0.06,
      lfoTarget: 'volume',
      octave: 0,
    },
  },
  {
    id: 'factory-trance-pluck',
    name: 'Trance Pluck',
    category: 'Pluck',
    isFactory: true,
    description: 'Ultra-fast saw pluck with high resonance envelope bite',
    params: {
      oscType: 'sawtooth',
      subOscVolume: 0.25,
      noiseVolume: 0.02,
      detune: 10,
      filterType: 'lowpass',
      filterCutoff: 3400,
      filterResonance: 5.0,
      filterEnvAmount: 3000,
      attack: 0.002,
      decay: 0.18,
      sustain: 0.02,
      release: 0.2,
      filterAttack: 0.002,
      filterDecay: 0.16,
      filterSustain: 0,
      filterRelease: 0.2,
      lfoRate: 1.0,
      lfoDepth: 0.0,
      lfoTarget: 'cutoff',
      octave: 0,
    },
  },
  {
    id: 'factory-noise-riser-fx',
    name: 'Noise Riser FX',
    category: 'FX',
    isFactory: true,
    description: 'Atmospheric building noise sweep for transitions and build-ups',
    params: {
      oscType: 'square',
      subOscVolume: 0.1,
      noiseVolume: 0.4,
      detune: 20,
      filterType: 'highpass',
      filterCutoff: 600,
      filterResonance: 4.5,
      filterEnvAmount: 2200,
      attack: 1.2,
      decay: 0.8,
      sustain: 0.7,
      release: 1.5,
      filterAttack: 1.5,
      filterDecay: 1.0,
      filterSustain: 0.5,
      filterRelease: 1.5,
      lfoRate: 6.0,
      lfoDepth: 0.35,
      lfoTarget: 'cutoff',
      octave: 0,
    },
  },
];

export const ALL_FACTORY_PRESETS: SynthPresetItem[] = [
  ...FACTORY_PRESETS,
  ...FACTORY_BASS_PRESETS,
];

export function getAllSynthPresets(custom: SynthPresetItem[]): SynthPresetItem[] {
  return [...custom, ...ALL_FACTORY_PRESETS];
}

export function findPresetByName(name: string, presets: SynthPresetItem[]): SynthPresetItem | undefined {
  if (!name) return undefined;
  return presets.find((p) => p.name === name);
}

export interface CategoryPresetGroup {
  category: SynthPresetCategory;
  label: string;
  badgeClass: string;
  description: string;
  presets: SynthPresetItem[];
}

/**
 * Organizes presets into structured categories ('Bass', 'Lead', 'Pad', 'Keys', 'Pluck', 'Brass', 'FX', 'User')
 * instead of a single flat list.
 */
export function getPresetsGroupedByCategory(allPresets: SynthPresetItem[]): CategoryPresetGroup[] {
  const order: SynthPresetCategory[] = ['Bass', 'Lead', 'Pad', 'Keys', 'Pluck', 'Brass', 'FX', 'User'];
  const groups: CategoryPresetGroup[] = [];

  for (const cat of order) {
    const meta = SYNTH_CATEGORIES.find((c) => c.id === cat) ?? {
      id: cat,
      label: cat,
      shortLabel: cat,
      badgeClass: 'badge badge-ghost',
      description: '',
    };

    const matching = allPresets.filter((p) => {
      if (cat === 'User') {
        return !p.isFactory || p.category === 'User';
      }
      return p.isFactory && p.category === cat;
    });

    if (matching.length > 0) {
      groups.push({
        category: cat,
        label: cat === 'User' ? `Custom / Saved (${matching.length})` : `${meta.label} (${matching.length})`,
        badgeClass: meta.badgeClass,
        description: meta.description,
        presets: matching,
      });
    }
  }

  return groups;
}

export function getCategoryMeta(category: SynthPresetCategory): SynthPresetCategoryMeta {
  return (
    SYNTH_CATEGORIES.find((c) => c.id === category) ?? {
      id: category,
      label: category,
      shortLabel: category,
      badgeClass: 'badge badge-ghost',
      description: '',
    }
  );
}
