// Regenerates src/utils/spellingCharacterizationFixture.ts.
// Run: bun run scripts/gen-spelling-characterization.ts > src/utils/spellingCharacterizationFixture.ts
//
// Every (root x scale) pair, not a sample: a sample would miss the
// double-accidental pairs — the only cases that exercise the fallback — and
// would miss F# major's E#, the case that proves single accidentals are kept.
import { SCALES } from '../src/data/scales';
import { ROOTS } from '../src/utils/musicTheory';
import { spellScaleNotes } from '../src/utils/noteSpelling';

const lines: string[] = [];
for (const root of ROOTS) {
  for (const scaleType of Object.keys(SCALES)) {
    lines.push(`  '${root}|${scaleType}': '${spellScaleNotes(root, scaleType).join(' ')}',`);
  }
}

console.log(`/**
 * GENERATED by scripts/gen-spelling-characterization.ts — do not hand-edit.
 * Every (root x scale) pair. Key: \`\${root}|\${scaleType}\`.
 */
export const SPELLING_CHARACTERIZATION: Record<string, string> = {
${lines.join('\n')}
};
`);
