// Regenerates src/utils/diatonicCharacterizationFixture.ts.
// Run: bun run scripts/gen-diatonic-characterization.ts > src/utils/diatonicCharacterizationFixture.ts
//
// The fixture is a characterization lock, not authored content: it is
// regenerated and the DIFF is reviewed. A key that moves without a decision
// behind it is the bug this file exists to make visible.
import { SCALES } from '../src/data/scales';
import { ROOTS, getDiatonicChordForDegree } from '../src/utils/musicTheory';

const lines: string[] = [];
for (const scaleType of Object.keys(SCALES)) {
  for (const root of ROOTS) {
    for (const use7ths of [false, true]) {
      const cells = SCALES[scaleType].intervals.map((_, degree) => {
        const chord = getDiatonicChordForDegree(degree, root, scaleType, use7ths);
        return `${chord.root}:${chord.quality}:${chord.degreeName}`;
      });
      lines.push(`  '${scaleType}|${root}|${use7ths ? '7' : '3'}': '${cells.join(' ')}',`);
    }
  }
}

console.log(`/**
 * GENERATED by scripts/gen-diatonic-characterization.ts — do not hand-edit.
 * Regenerate and review the diff; a moved key is a behaviour change.
 *
 * Key: \`\${scaleType}|\${root}|\${'3' triads | '7' sevenths}\`
 * Value: one \`root:quality:degreeName\` cell per scale degree, space-joined.
 */
export const DIATONIC_CHARACTERIZATION: Record<string, string> = {
${lines.join('\n')}
};
`);
